spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/cb_shop'
    username: root
    password: '806127059'
  # Hibernate ddl auto
  jpa:
    hibernate:
      ddl-auto: update
  #Email Properties
  mail:
    host: smtp.gmail.com
    port: '587'
    username: real.cbshop@gmail.com
    password: qifuhjxtqolferic
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      springframework:
        web: trace
      hibernate: error
    com:
      cbshop:
        demo: debug
  file:
    name: cbshop.log
server:
  error:
    include-message: always